### ISSUE TITLE
Solve java related quality issues

### ISSUE THREAD

**Issue by davidbinderRTE** [opfab/operatorfabric-core#13]
Head ticket for the following quality related tickets

* [x] #10 Solve sonar java raised bugs for 0.0.1.RELEASE
* [x] #11 Solve sonar java raised vulnerabilities for 0.0.1.RELEASE
* [x] #12 Solve sonar java test coverage gap for 0.0.1.RELEASE
* [x] #14 Solve sonar java raised code smells for 0.0.1.RELEASE

**Comment by davidbinderRTE** [comment]
The major step is reached, now technical debt must be kept low
