### ISSUE TITLE
Support external devices for notifications - initial set up for the back end

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [opfab/operatorfabric-core#1862]
Some use cases require the sound notifications associated with some cards to be played on external devices (usually shared in the control room) rather than in the browser.

The scope of this issue is to create the initial scaffolding for a service that would act as an interface with these devices. It needs to be generic enough so drivers for different types of devices can be injected.

### External devices service
- [x] Create new Spring Boot microservice
- [x] Add it to current build
- [x] Modify nginx conf & templates
- [x] Modify port table
- [x] Add it to current docker-composes
- [x] Rework build and structure and take service out of core (and it shouldn't have to be suffixed with "business-service")
- [x] Expose API to trigger handling of notification by external device (playing of sound for example)

### Modbus driver
- [x] Create modbus server as driver for sound device (separate repo) ?
- [x] Test it against sound device stub
- [x] Close connection properly

### Dummy modbus device (writing to log)
- [x] Get master to write things on dummy device
- [x] Make it work with docker
- [x] Host&Port vs Server address

#### Devices
- [x] Define device configuration object model
- [x] Allow it to be loaded from a configuration file (json?, yml props?)
- [x] Set up basic structure for API management
#### Signal mapping
- [x] Define device configuration object model
- [x] Allow it to be loaded from a configuration file (json?, yml props?)
- [x] Set up basic structure for API management
#### User configuration (which device they can use)
- [x] Define device configuration object model
- [x] Allow it to be loaded from a configuration file (json?, yml props?)
- [x] Set up basic structure for API management

### Misc
- [x] Use synchronized on drivers?
- [x] Bug with dynamically resolved hosts (docker containers)
- [ ] Karate Tests
- [ ] Implement cache (look at UserServiceCache) for config retrieval/resolution
- [ ] Complete external devices configuration APIs
- [ ]  & associated karate tests
- [ ] Add PATCH for configuration management endpoints (x3)
- [ ] Remove temporary testing stuff
- [ ] Add list of users to device object
- [ ] ReadTimeout on dummy client
- [ ] Handle error/response from post notification in the front

### TODOs
- API examples
- For all controllers, add "non OK" return types (bad request, 403 forbidden, 404 not found etc.)
- For all controllers, check that return codes defined as possible in swagger match those returned by controller
- For all controllers, summary vs description?
- For all controllers, patch & delete
- For all controllers, set up restrictions (admin?)
- Doc: Async not needed on device service as the calls from the front are already non-blocking. And this way we know if something is wrong
- Check copyrights

**Comment by AlexGuironnetRTE** [comment]
When trying to integrate the jlibmodbus dependency the build fails with the following message:

```
> Task :services:core:external-devices-business-service:compileJava FAILED
Errors occurred while build effective model from /home/guironnetale/.gradle/caches/modules-2/files-2.1/com.intelligt.modbus/jlibmodbus/1.2.9.7/cfd3f011505c66194e0fe32dd25ec77e15d3b327/jlibmodbus-1.2.9.7.pom:
'dependencies.dependency.systemPath' for javax.comm:comm:jar must specify an absolute path but is ${project.basedir}/lib/comm.jar in com.intelligt.modbus:jlibmodbus:1.2.9.7
/home/guironnetale/Projects/opfab/operatorfabric-core/services/core/external-devices/src/main/java/org/opfab/externaldevices/drivers/ModbusMasterDummy.java:3: error: cannot find symbol
import com.intelligt.modbus.jlibmodbus.ModbusMaster;
```

This is due to kochedykov/jlibmodbus#24

This as been fixed on the main branch but not released yet (see kochedykov/jlibmodbus#54 about next release). My workaround so far is to package a SNAPSHOT version of the lib from the latest commit and retrieve it from my local Maven repository but we will need to find a cleaner solution if the official release doesn't come soon.
