### ISSUE TITLE
Configure Travis CI

### ISSUE THREAD

**Issue by davidbinderRTE** [opfab/operatorfabric-core#2]
This is the header task for the following travis configuration subtasks

* [x] #3 Init Travis
* [x] #4 configure e2e test with docker containers in Travis CI
* [x] #5 Configure quality with SonarQube & Travis CI
* [x] #6 Intégrate ng build with Travis CI
* [x] #7 Intégrate ng tests with Travis CI
* [x] #8 Intégrate ng quality with Travis CI/SonarQube
