### ISSUE TITLE
As an Operator, I want to be fed with relevant Cards

### ISSUE THREAD

**Issue by davidbinderRTE** [opfab/operatorfabric-core#22]
Once authenticated, an operator needs to access the card feed. The card feed provides the Operator with relevant card.
A "relevant card" is a card for which the operator is either:

- the main recipient or a recipient
- part of at least one group recipient

A recipient is an Operator or Group which is concerned by the card
A main recipient is an Operator that is supposed the handle the card himself

NB: not all cards have main recipient but all cards accessible to an operator have recipient.

The following Tasks and user stories are sub task to this user story:

* [x] #23 As an Operator I want to be updated with relevant cards (US)
* [x] #24 As an Operator I want to access cards previously published (US)
* [x] #27 Display the cards as a Feed (Task)
* [ ] #43 As an Operator, I want the feed to be displayed sorted
* [x] #1 Integrate with Card SSE endpoint (Task)
