### ISSUE TITLE
As an operator, I want to access Third Party Specific web pages

### ISSUE THREAD

**Issue by davidbinderRTE** [opfab/operatorfabric-core#48]
The Operator may access predefine webpages throught URLs referenced in a menu.

If a Third Party Service define one menu item, it is displayed as a first level operator fabric main menu item. Otherwise a first level menu item named by the name of the service unfold into a submenu listing all URL.

Each menu item is define by:
- a unique id (relative to the Third Party Service)
- URL
- a i18n key used for label

Related tickets:
- [ ] #50 Add menu entries to Third model
- [ ] #49 Add Third Party Service menu entries
- [ ] #51 Add an i18n label to the third class
- [ ] #59 Add Third Party menu entries to navbar
